let
    Source = GoogleBigQuery.Database([BillingProject="converged-havas-de"]),
    #"converged-havas-de" = Source{[Name="converged-havas-de"]}[Data],
    yougov_integration_Schema = #"converged-havas-de"{[Name="yougov",Kind="Schema"]}[Data],
    subvariable_dim_Table = yougov_integration_Schema{[Name="entity_dim",Kind="Table"]}[Data],
    #"Filtered Rows" = Table.SelectRows(subvariable_dim_Table, each ([cat1] = "Audiences")),
    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows",{"cat1", "cat3", "cat4", "name", "description", "entity_name", "id"})
in
    #"Removed Other Columns"